version: '3.8'

services:
  # THE FIRST CONCERN: THE SOURCE (BACKEND)
  source:
    build: .
    ports:
      - "5000:5000"

  # THE SECOND CONCERN: THE INTERFACE (FRONTEND)
  interface:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - source